apiVersion: v1
kind: Secret
metadata:
  name: tradeup-secrets
  namespace: tradeup
type: Opaque
data:
  DATABASE_URL: postgresql://neondb_owner:npg_viZPT7OtF4xW@ep-proud-firefly-ah45z6zn-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
  POSTGRES_PASSWORD: tradeup123
  JWT_SECRET: J2wtsecxret
  SUPABASE_URL: https://prhkliftqgzbnofocshy.supabase.co
  SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByaGtsaWZ0cWd6Ym5vZm9jc2h5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NDM0ODk5NiwiZXhwIjoyMDc5OTI0OTk2fQ.45qzI9-EwKZOL9BwDGhGYIZQvfLy0NKS_4Kx6jU_lUU
  NEWS_API_KEY: EBqVj2NM0RvmMOdf8l1FEw3aI4keyF8n
  STOCK_API_KEY: FjJNWgz1yzC9t4BypoM7PZO3jyZCYIVY203V7OpM
  GEMINI_API_KEY: AIzaSyDEWtP2vkpCFvgJXF8xrweda9AXEtpktWI
 
