export const FEATURED_SYMBOLS = [
  'ABL',
  'ABOT',
  'AGP',
  'AHCL',
  'AICL',
  'AIRLINK',
  'AKBL',
  'APL',
  'ATLH',
  'ATRL',
  'BAFL',
  'BAHL',
  'BNWM',
  'BOP',
  'BWCL',
  'CHCC',
  'CNERGY',
  'COLG',
  'CPHL',
  'DCR',
  'DGKC',
  'EFERT',
  'ENGROH',
  'FABL',
  'FATIMA',
  'FCCL',
  'FFC',
  'FFL',
  'FHAM',
  'GADT',
  'GAL',
  'GHGL',
  'GHNI',
  'GLAXO',
  'HALEON',
  'HBL',
  'HCAR',
  'HINOON',
  'HMB',
  'HUBC',
  'HUMNL',
  'IBFL',
  'ILP',
  'INDU',
  'INIL',
  'ISL',
  'JDWS',
  'JVDC',
  'KAPCO',
  'KEL',
  'KOHC',
  'KTML',
  'LCI',
  'LOTCHEM',
  'LUCK',
  'MARI',
  'MCB',
  'MEBL',
  'MEHT',
  'MLCF',
  'MTL',
  'MUREB',
  'NATF',
  'NBP',
  'NESTLE',
  'NML',
  'NPL',
  'OGDC',
  'PABC',
  'PAEL',
  'PAKT',
  'PGLC',
  'PIBTL',
  'PIOC',
  'PKGS',
  'POL',
  'POWER',
  'PPL',
  'PSEL',
  'PSO',
  'PSX',
  'PTC',
  'RMPL',
  'SAZEW',
  'SCBPL',
  'SEARL',
  'SHFA',
  'SNGP',
  'SRVI',
  'SSGC',
  'SSOM',
  'SYS',
  'TGL',
  'THALL',
  'TPLRF1',
  'TRG',
  'UBL',
  'UPFL',
  'YOUW',
] as const;

export type FeaturedSymbol = (typeof FEATURED_SYMBOLS)[number];

export const PSX_API_BASE =
  process.env.PSX_API_BASE || 'https://psxterminal.com';
export const PSX_WS_URL = 'wss://psxterminal.com/';

export const SYMBOL_NAME_MAP: Record<string, string> = {
  ABL: 'Allied Bank Ltd.',
  ABOT: 'Abbott Laboratories (Pak) Ltd.',
  AGP: 'AGP Ltd.',
  AHCL: 'Arif Habib Corporation Ltd.',
  AICL: 'Adamjee Insurance Company Ltd.',
  AIRLINK: 'Air Link Communication Ltd',
  AKBL: 'Askari Bank Ltd.',
  APL: 'Attock Petroleum Ltd.',
  ATLH: 'Atlas Honda Ltd.',
  ATRL: 'Attock Refinery Ltd.',
  BAFL: 'Bank Alfalah Ltd.',
  BAHL: 'Bank AL-Habib Ltd.',
  BNWM: 'Bannu Woollen Mills Ltd.',
  BOP: 'The Bank Of Punjab',
  BWCL: 'Bestway Cement Ltd',
  CHCC: 'Cherat Cement Company Ltd.',
  CNERGY: 'Cnergyico Pk Ltd.',
  COLG: 'Colgate Palmolive (Pak) Ltd.',
  CPHL: 'Citi Pharma Ltd.',
  DCR: 'Dolmen City Reit',
  DGKC: 'D. G. Khan Cement Company Ltd.',
  EFERT: 'Engro Fertilizers Ltd.',
  ENGROH: 'Engro Holding Ltd.',
  FABL: 'Faysal Bank Ltd.',
  FATIMA: 'Fatima Fertilizer Company Ltd.',
  FCCL: 'Fauji Cement Company Ltd.',
  FFC: 'Fauji Fertilizer Company Ltd.',
  FFL: 'Fauji Foods Ltd.',
  FHAM: 'First Habib Modarba Ltd.',
  GADT: 'Gadoon Textile Mills Ltd.',
  GAL: 'Ghandhara Automobiles Ltd.',
  GHGL: 'Ghani Glass Ltd.',
  GHNI: 'Ghandhara Industries Ltd.',
  GLAXO: 'Glaxosmithkline (Pak) Ltd.',
  HALEON: 'Haleon Pakistan Ltd.',
  HBL: 'Habib Bank Ltd.',
  HCAR: 'Honda Atlas Cars (Pakistan) Ltd.',
  HINOON: 'Highnoon Laboratories Ltd.',
  HMB: 'Habib Metropolitan Bank Ltd.',
  HUBC: 'The Hub Power Company Ltd.',
  HUMNL: 'Hum Network Ltd.',
  IBFL: 'Ibrahim Fibre Ltd.',
  ILP: 'Interloop Limited',
  INDU: 'Indus Motor Company Ltd.',
  INIL: 'International Industries Ltd.',
  ISL: 'International Steels Ltd.',
  JDWS: 'JDW Sugar Mills Ltd.',
  JVDC: 'Javedan Corporation Ltd.',
  KAPCO: 'Kot Addu Power Company Ltd.',
  KEL: 'K-Electric Ltd.',
  KOHC: 'Kohat Cement Company Ltd.',
  KTML: 'Kohinoor Textile Mills Ltd.',
  LCI: 'Lucky Core Industries Ltd.',
  LOTCHEM: 'Lotte Chemical (Pak) Ltd.',
  LUCK: 'Lucky Cement Ltd.',
  MARI: 'Mari Energies Limited',
  MCB: 'MCB Bank Ltd.',
  MEBL: 'Meezan Bank Ltd.',
  MEHT: 'Mehmood Textile Mills Ltd.',
  MLCF: 'Maple Leaf Cement Factory Ltd.',
  MTL: 'Millat Tractors Ltd.',
  MUREB: 'Murree Brewery Company Ltd.',
  NATF: 'National Foods Ltd.',
  NBP: 'National Bank Of Pakistan',
  NESTLE: 'Nestle Pakistan Ltd.',
  NML: 'Nishat Mills Ltd.',
  NPL: 'Nishat Power Ltd.',
  OGDC: 'Oil & Gas Development Company Ltd.',
  PABC: 'Pakistan Aluminium Beverage Cans Ltd.',
  PAEL: 'Pak Elektron Ltd.',
  PAKT: 'Pakistan Tobacco Company Ltd.',
  PGLC: 'Pak Gulf Leasing Co. Ltd.',
  PIBTL: 'Pakistan International Bulk Terminal Ltd.',
  PIOC: 'Pioneer Cement Ltd.',
  PKGS: 'Packages Ltd.',
  POL: 'Pakistan Oilfields Ltd.',
  POWER: 'Power Cement Ltd.',
  PPL: 'Pakistan Petroleum Ltd.',
  PSEL: 'Pakistan Services Ltd.',
  PSO: 'Pakistan State Oil Company Ltd.',
  PSX: 'Pakistan Stock Exchange Ltd.',
  PTC: 'Pakistan Telecommunication Co. Ltd.',
  RMPL: 'Rafhan Maize Products Co. Ltd.',
  SAZEW: 'Sazgar Engineering Works Ltd.',
  SCBPL: 'Standard Chartered Bank Pakistan Ltd.',
  SEARL: 'The Searle Company Ltd.',
  SHFA: 'Shifa International Hospitals Ltd.',
  SNGP: 'Sui Northern Gas Pipelines Ltd.',
  SRVI: 'Service Industries Ltd.',
  SSGC: 'Sui Southern Gas Company Ltd.',
  SSOM: 'S. S. Oil Mills Ltd.',
  SYS: 'Systems Ltd.',
  TGL: 'Tariq Glass Industries Ltd.',
  THALL: 'Thal Ltd.',
  TPLRF1: 'TPL REIT Fund I',
  TRG: 'TRG Pakistan Ltd.',
  UBL: 'United Bank Ltd.',
  UPFL: 'Unilever Pakistan Foods Ltd.',
  YOUW: 'Yousuf Weaving Mills Ltd.',
};
