apiVersion: v1
kind: Service
metadata:
  name: tradeup-backend-svc
  namespace: tradeup
  annotations:
    cloud.google.com/backend-config: '{"default": "tradeup-backend-config"}'
spec:
  type: NodePort # Required for GKE Ingress HTTP Load Balancer
  selector:
    app: tradeup-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
