steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'Prototype/frontend'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/project-8ca874ae-688d-414c-91b/tradeup/frontend:latest', '.']
images:
  - 'us-central1-docker.pkg.dev/project-8ca874ae-688d-414c-91b/tradeup/frontend:latest'
options:
  logging: CLOUD_LOGGING_ONLY
