steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/project-8ca874ae-688d-414c-91b/github.com/um3rz/tradeup/frontend:latest', './frontend']
images:
  - 'gcr.io/project-8ca874ae-688d-414c-91b/github.com/um3rz/tradeup/frontend:latest'
options:
  logging: CLOUD_LOGGING_ONLY
